DROP TABLE IF EXISTS earthquakes;
CREATE TABLE earthquakes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT,
    country TEXT,
    region TEXT,
    depth INTEGER,
    magnitude TEXT,
    deaths INTEGER
);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2023-16-07','USA','Alaska Peninsula',32,'7.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2022-20-12','USA','Humboldt County',17,'6.4',2);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2021-29-07','USA','Alaska Peninsula',32,'8.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2020-19-10','USA','Alaska',33,'7.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2020-09-08','USA','Sparta',8,'5.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2020-22-07','USA','Alaska',28,'7.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2020-18-03','USA','Utah',12,'5.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2019-06-07','USA','Ridgecrest',8,'7.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2019-04-07','USA','Ridgecrest,Nevada',11,'6.4',1);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2018-30-11','USA','Anchorage',54,'7.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2018-04-05','USA','Puna District',2,'6.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2018-04-03','USA','Breckenridge, Enid',5,'4.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2018-23-01','USA','Kodiak Island',14,'7.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2016-07-11','USA','Cushing',7,'5.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2016-24-01','USA','Kenai',56,'7.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2015-27-07','USA','Alaska',NULL,'6.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2014-24-08','USA','Napa, Vallejo',6,'6.1',1);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2014-25-07','USA','Southeastern',12,'6.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2014-15-07','USA','Harrah',56,'3.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2014-23-06','USA','Aleutian Islands',7,'7.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2014-29-03','USA','La Habra, Brea, Fullerton',12,'5.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2014-09-02','USA','Guthrie',49,'4.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2013-18-04','USA','West',38,'2.1',14);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2013-05-01','USA','Southeastern',19,'7.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2011-08-11','USA','Sparks, Prague',57,'5.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2011-06-11','USA','Sparks',10,'5.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2011-02-09','USA','Aleutian Islands (Fox Islands)',53,'6.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2011-23-08','USA','Louisa County, Maryland, Washington D.C.',4,'5.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2011-23-08','USA','Segundo',18,'5.4',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2011-24-06','USA','Aleutian Islands (Fox Islands)',39,'7.3',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2011-17-02','USA','Paonia',21,'3.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2010-19-12','USA','Luther',30,'3.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2010-15-06','USA','Ocotillo',58,'5.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2010-10-01','USA','Off Coast Northern',39,'6.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2008-29-07','USA','Los Angeles',15,'5.4',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2008-26-04','USA','Fallon',10,'5.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2008-18-04','USA','West Salem',59,'5.3',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2008-21-02','USA','Wells',2,'6.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2007-31-10','USA','San Jose',54,'5.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2007-17-08','USA','Utah',56,'1.6',3);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2007-06-08','USA','Huntington',40,'4.2',9);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2007-02-08','USA','Aleutian Islands',42,'6.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2007-20-07','USA','Montclair',22,'4.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2007-08-05','USA','Sheridan',49,'4.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2006-15-10','USA','Hawaiian Islands',49,'6.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2005-26-07','USA','Dillon, Silver Star, Twin Bridges',37,'5.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2005-15-06','USA','Off Coast Northern',53,'7.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2004-28-09','USA','Central (Parkfield, San Miguel)',24,'6.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2003-22-12','USA','Paso Robles, templeton, atascadero',56,'6.6',2);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2003-17-11','USA','Aleutian Islands (Rat Islands)',6,'7.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2003-06-06','USA','Bardwell',34,'4.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2003-29-04','USA','Fort Payne, gaylesville, valley Head',39,'4.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2003-22-02','USA','Big Bear City',10,'5.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2002-03-11','USA','Slana, Mentasta Lake, Fairbanks',41,'7.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2002-23-10','USA','Cantwell, Denali Natl Park',19,'6.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2002-20-04','USA','Clinton, Essex, Au Sable Forks',47,'5.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2001-09-09','USA','Los Angeles',18,'4.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2001-28-02','USA','Olympia, Seattle, Tacoma',32,'6.8',1);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('2000-03-09','USA','Napa',30,'5.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1999-16-10','USA','Ludlow, Landers, Twentynine Palms',44,'7.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1996-10-06','USA','Andreanof Islands',35,'7.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1996-10-06','USA','Andreanof Islands',56,'7.3',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1995-06-10','USA','Fairbanks North Star County',18,'6.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1994-26-12','USA','Eureka, Samoa, Arcata, Blue Lake',29,'5.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1994-01-09','USA','North (Honeydew)',53,'7.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1994-03-02','USA','Afton',4,'5.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1994-17-01','USA','Northridge',55,'6.7',60);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1994-16-01','USA','Reading, Felt To Canada',16,'4.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1993-21-09','USA','Klamath Falls',55,'6.0',2);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1993-25-03','USA','Washington-Oregon Border',35,'5.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1992-29-06','USA','Nevada Test Site',22,'5.4',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1992-28-06','USA','Landers, Yucca Valley',34,'7.6',3);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1992-28-06','USA','Big Bear Lake, Big Bear City',30,'6.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1992-25-04','USA','Humboldt County (Ferndale, Petrolia)',4,'7.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1992-23-04','USA','Joshua Tree, Angelus Oaks',23,'6.3',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1991-17-08','USA','Honeydew, Whitethorn, Petrolia',40,'6.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1991-28-06','USA','Arcadia, Glendale, Los Angeles',54,'5.1',2);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1990-28-02','USA','S, Claremont, Covina',36,'5.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1989-18-10','USA','Loma Prieta',15,'6.9',62);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1989-04-09','USA','Alaska',58,'6.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1989-26-06','USA','Puna District',3,'6.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1988-06-03','USA','Gulf Of Alaska (Anchorage)',36,'7.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1987-30-11','USA','Yakutat',19,'7.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1987-24-11','USA','Superstition Hills',14,'6.2',2);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1987-17-11','USA','Gulf Of Alaska',53,'7.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1987-04-10','USA','Whittier, Pasadena',38,'4.8',1);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1987-01-10','USA','Whittier',20,'5.7',8);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1986-21-07','USA','Chalfant Valley',26,'6.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1986-13-07','USA','San Diego, Newport Beach',8,'5.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1986-08-07','USA','Palm Springs',44,'6.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1986-17-05','USA','Andreanof Islands',22,'6.4',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1986-07-05','USA','Aleutian Islands (Adak)',10,'8.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1984-18-10','USA','Douglas, Medicine Bow',23,'5.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1984-24-04','USA','Central (Morgan Hill)',19,'6.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1983-16-11','USA','Kapapala',NULL,'6.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1983-28-10','USA','Borah Peak, Challis, Mackay',6,'7.3',2);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1983-12-07','USA','Prince William Sound',3,'6.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1983-02-05','USA','Central, Coalinga',37,'6.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1981-26-04','USA','Westmorland, calipatria',28,'6.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1980-08-11','USA','North Coast',34,'7.2',5);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1980-27-07','USA','Maysville',21,'5.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1980-25-05','USA','Mammoth Lakes',44,'6.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1980-18-05','USA','Mt St Helens',11,'5.2',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1980-24-01','USA','Livermore',9,'5.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1979-15-10','USA','Imperial Valley, Mexico (Mexicali)',54,'6.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1979-28-02','USA','Alaska',8,'7.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1978-13-08','USA','Southern',53,'5.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1975-29-11','USA','Hawaii',40,'7.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1975-01-08','USA','Oroville',12,'5.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1975-28-03','USA','Pocatello Valley',5,'6.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1975-02-02','USA','Aleutian Islands (Near Islands)',39,'7.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1973-26-04','USA','Hilo',28,'6.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1973-21-02','USA','Oxnard',57,'5.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1972-30-07','USA','Sitka, Juneau',14,'7.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1971-06-11','USA','Aleutian Islands (Rat Islands)',NULL,'5.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1971-02-05','USA','Andreanof Islands',27,'7.1',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1971-09-02','USA','San Fernando',41,'6.5',65);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1970-11-03','USA','Andreanof Islands',34,'6.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1969-02-10','USA','Santa Rosa',46,'4.8',1);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1965-02-07','USA','Aleutian Islands (Fox Islands)',38,'6.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1965-29-04','USA','Seattle',43,'6.6',7);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1965-30-03','USA','Aleutian Islands (Rat Islands)',3,'7.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1965-04-02','USA','Aleutian Islands (Rat Islands)',21,'8.7',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1964-28-03','USA','Alaska',NULL,'9.2',15);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1962-21-12','USA','Aleutian Islands (Fox Islands)',43,'6.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1962-30-08','USA','Utah',NULL,'5.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1961-04-04','USA','Terminal Island',NULL,'0.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1959-18-08','USA','Hebgen Lake',13,'7.7',28);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1958-10-07','USA','Lituya Bay',59,'7.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1957-22-03','USA','Aleutian Islands (Fox Islands)',NULL,'7.5',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1957-09-03','USA','Alaska',31,'8.6',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1955-25-01','USA','Terminal Island',NULL,'0.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1954-16-12','USA','Dixie Valley',NULL,'7.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1954-23-08','USA','Stillwater Range',NULL,'6.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1954-06-07','USA','Fallon',NULL,'6.8',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1952-22-08','USA','Kern County',24,'5.8',2);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1952-21-07','USA','Kern County',14,'7.7',12);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1952-17-03','USA','Hawaii',NULL,'0.0',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1951-21-08','USA','Hawaii',NULL,'6.9',0);
INSERT INTO earthquakes (date,country,region,depth,magnitude,deaths) VALUES ('1951-15-08','USA','Terminal Island',NULL,'0.0',0);